apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhacs-policies
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: stackrox
    server:  https://kubernetes.default.svc
  project: default
  source:
    path: policies
    repoURL: https://github.com/shaneboulden/stackrox-policy-as-code.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
