kind: SecurityPolicy
apiVersion: config.stackrox.io/v1alpha1
metadata:
  name: cve-2025-23089
spec:
  policyName: 'CVE-2025-23089: End-of-Life Node.js Versions Pose Security Risks'
  categories:
    - 'Vulnerability Management'
  description: 'A flaw was found in Node.js. This vulnerability allows potential exposure to unaddressed software vulnerabilities via the continued use of End-of-Life (EOL) versions that no longer receive security updates or patches.'
  disabled: false
  guidance: Use your package manager to update packages
  lifecycleStages:
    - BUILD
    - DEPLOY
  policySections:
    - sectionName: "Rule 1"
      policyGroups:
        - fieldName: CVE
          booleanOperator: OR
          negate: false
          values:
            - value: 2025-23089
  rationale: Important CVEs should be patched
  severity: HIGH_SEVERITY
