---
- hosts: all
  become: false
  vars:
    stackrox_policy_cr:
    file_name:
    git_message:
  tasks:
    - name: Git checkout
      ansible.builtin.git:
        repo: 'https://github.com/shaneboulden/stackrox-policy-as-code'
        dest: /tmp/checkout
        version: main

    - name: Git config email
      community.general.git_config:
        name: user.email
        repo: /tmp/checkout
        scope: local
        value: "ansible@{{ ansible_fqdn }}"

    - name: Git config username
      community.general.git_config:
        name: user.username
        repo: /tmp/checkout
        scope: local
        value: "ansible"
  
    - name: Create a new random identifier
      command: "echo pac-updates-{{ lookup('ansible.builtin.password', '/dev/null', length=5, chars='digits') }}"
      register: output

    - name: show branch
      debug: var=output
  
    - name: Create a new branch
      shell: 
        cmd: git checkout -b "{{ output.stdout }}"
        chdir: /tmp/checkout
  
    - name: Add new file for the update
      template:
        src: new-policy.j2
        dest: "/tmp/checkout/policies/{{ file_name }}"
        mode: 644
  
    - name: Create a new commit
      shell: 
        cmd: git add policies/{{ file_name }} && git commit -m "{{ git_message }}"
        chdir: /tmp/checkout
  
    - name: Push new changes
      shell: 
        cmd: git push origin "{{ output.stdout }}"
        chdir: /tmp/checkout

