kind: SecurityPolicy
apiVersion: config.stackrox.io/v1alpha1
metadata:
  name: nodejs-unsupported
spec:
  policyName: 'Unsupported NodeJS Versions'
  categories:
    - 'Package Management'
  description: 'This policy flags unsupported NodeJS versions'
  disabled: false
  enforcementActions:
    - SCALE_TO_ZERO_ENFORCEMENT
    - FAIL_BUILD_ENFORCEMENT
    - FAIL_DEPLOYMENT_CREATE_ENFORCEMENT
  remediation: 'Use a supported version of Node.js. Supported versions can be found at https://nodejs.org/en/about/previous-releases'
  lifecycleStages:
    - BUILD
    - DEPLOY
  policySections:
    - sectionName: "Rule 1"
      policyGroups:
        - fieldName: Image Component
          booleanOperator: OR
          negate: false
          values:
            - value: nodejs=1\:16.*
  rationale: 'Unsupported Node.js versions are potentially vulnerable to critical vulnerabilties'
  severity: 'HIGH_SEVERITY'